// --- ステータス定義（略称＋ツールチップ＋レベル値） ---
const STAT_MASTER = [
  {
    "正式名称": "物理攻撃力",
    "UI略称": "物攻",
    "ツールチップ（hoverで表示）": "Physical Attack",
    "備考": "標準",
    "lv.60": 66,
    "lv75": 82.5,
    "lv.100": 110,
    "lv.110": 121
  },
  {
    "正式名称": "物理防御力",
    "UI略称": "物防",
    "ツールチップ（hoverで表示）": "Physical Defense",
    "備考": "標準",
    "lv.60": 66,
    "lv75": 82.5,
    "lv.100": 110,
    "lv.110": 121
  },
  {
    "正式名称": "魔法攻撃力",
    "UI略称": "魔攻",
    "ツールチップ（hoverで表示）": "Magic Attack",
    "備考": "標準",
    "lv.60": 66,
    "lv75": 82.5,
    "lv.100": 110,
    "lv.110": 121
  },
  {
    "正式名称": "魔法防御力",
    "UI略称": "魔防",
    "ツールチップ（hoverで表示）": "Magic Defense",
    "備考": "標準",
    "lv.60": 66,
    "lv75": 82.5,
    "lv.100": 110,
    "lv.110": 121
  },
  {
    "正式名称": "HP",
    "UI略称": "HP",
    "ツールチップ（hoverで表示）": "Hit Points",
    "備考": "略称不要",
    "lv.60": 600,
    "lv75": 750,
    "lv.100": 1000,
    "lv.110": 1100
  },
  {
    "正式名称": "MP",
    "UI略称": "MP",
    "ツールチップ（hoverで表示）": "Mana Points",
    "備考": "略称不要",
    "lv.60": 600,
    "lv75": 750,
    "lv.100": 1000,
    "lv.110": 1100
  },
  {
    "正式名称": "HP再生",
    "UI略称": "HP再",
    "ツールチップ（hoverで表示）": "HP Regen",
    "備考": "ゲームUI定番",
    "lv.60": 54,
    "lv75": 67.5,
    "lv.100": 90,
    "lv.110": 99
  },
  {
    "正式名称": "MP再生",
    "UI略称": "MP再",
    "ツールチップ（hoverで表示）": "MP Regen",
    "備考": "定番",
    "lv.60": 54,
    "lv75": 67.5,
    "lv.100": 90,
    "lv.110": 99
  },
  {
    "正式名称": "回復倍率",
    "UI略称": "回復",
    "ツールチップ（hoverで表示）": "Healing Bonus",
    "備考": "すっきりする",
    "lv.60": 0.1,
    "lv75": 0.1,
    "lv.100": 0.1,
    "lv.110": 0.1
  },
  {
    "正式名称": "命中",
    "UI略称": "命中",
    "ツールチップ（hoverで表示）": "Accuracy",
    "備考": "OK",
    "lv.60": 42,
    "lv75": 52.5,
    "lv.100": 70,
    "lv.110": 77
  },
  {
    "正式名称": "回避",
    "UI略称": "回避",
    "ツールチップ（hoverで表示）": "Evasion",
    "備考": "OK",
    "lv.60": 36,
    "lv75": 45,
    "lv.100": 60,
    "lv.110": 66
  },
  {
    "正式名称": "移動速度",
    "UI略称": "移速",
    "ツールチップ（hoverで表示）": "Movement Speed",
    "備考": "UI向き",
    "lv.60": 4,
    "lv75": 4,
    "lv.100": 4,
    "lv.110": 4
  },
  {
    "正式名称": "クリティカル発生率",
    "UI略称": "クリ率",
    "ツールチップ（hoverで表示）": "Critical Hit Rate",
    "備考": "一番わかりやすい",
    "lv.60": 0.1,
    "lv75": 0.1,
    "lv.100": 0.1,
    "lv.110": 0.1
  },
  {
    "正式名称": "クリティカル倍率",
    "UI略称": "クリ倍",
    "ツールチップ（hoverで表示）": "Critical Damage",
    "備考": "定番略称",
    "lv.60": 0.05,
    "lv75": 0.05,
    "lv.100": 0.05,
    "lv.110": 0.05
  }
];

// --- パワーストーン定義（魔攻/物防 修正済み） ---
const POWER_STONE_MASTER = [
  {
    "パワーストーン": "物理攻撃",
    "UI略称": "物攻",
    "ツールチップ（hoverで表示）": "Physical Attack",
    "lv.60": 21,
    "lv.75": 26,
    "lv.100": 32,
    "lv.110": 38
  },
  {
    "パワーストーン": "魔法攻撃",
    "UI略称": "魔攻",
    "ツールチップ（hoverで表示）": "Magic Attack",
    "lv.60": 21,
    "lv.75": 26,
    "lv.100": 32,
    "lv.110": 38
  },
  {
    "パワーストーン": "物理防御",
    "UI略称": "物防",
    "ツールチップ（hoverで表示）": "Physical Defense",
    "lv.60": 21,
    "lv.75": 26,
    "lv.100": 32,
    "lv.110": 38
  },
  {
    "パワーストーン": "魔法防御",
    "UI略称": "魔防",
    "ツールチップ（hoverで表示）": "Magic Defense",
    "lv.60": 21,
    "lv.75": 26,
    "lv.100": 32,
    "lv.110": 38
  },
  {
    "パワーストーン": "HP",
    "UI略称": "HP",
    "ツールチップ（hoverで表示）": "Hit Points",
    "lv.60": 350,
    "lv.75": 450,
    "lv.100": 600,
    "lv.110": 750
  },
  {
    "パワーストーン": "MP",
    "UI略称": "MP",
    "ツールチップ（hoverで表示）": "Mana Points",
    "lv.60": 175,
    "lv.75": 225,
    "lv.100": 300,
    "lv.110": 375
  },
  {
    "パワーストーン": "HP回復",
    "UI略称": "HP再",
    "ツールチップ（hoverで表示）": "HP Regen",
    "lv.60": 12,
    "lv.75": 13,
    "lv.100": 14,
    "lv.110": 15
  },
  {
    "パワーストーン": "MP回復",
    "UI略称": "MP再",
    "ツールチップ（hoverで表示）": "MP Regen",
    "lv.60": 12,
    "lv.75": 13,
    "lv.100": 14,
    "lv.110": 15
  },
  {
    "パワーストーン": "命中率",
    "UI略称": "命中",
    "ツールチップ（hoverで表示）": "Accuracy",
    "lv.60": 8,
    "lv.75": 9,
    "lv.100": 9,
    "lv.110": 9
  },
  {
    "パワーストーン": "回避率",
    "UI略称": "回避",
    "ツールチップ（hoverで表示）": "Evasion",
    "lv.60": 6,
    "lv.75": 7,
    "lv.100": 7,
    "lv.110": 7
  },
  {
    "パワーストーン": "クリティカル率",
    "UI略称": "クリ率",
    "ツールチップ（hoverで表示）": "Critical Hit Rate",
    "lv.60": 1.1,
    "lv.75": 1.2,
    "lv.100": 1.3,
    "lv.110": 1.3
  },
  {
    "パワーストーン": "クリティカル防御率",
    "UI略称": "クリ倍",
    "ツールチップ（hoverで表示）": "Critical Damage",
    "lv.60": 0.9,
    "lv.75": 1,
    "lv.100": 1,
    "lv.110": 1
  }
];

// --- タリスマン定義（そのまま貼り込み） ---
const TALISMAN_MASTER = [
  {
    "Talisman": "ソブリンの遺産",
    "Talisman_en": "Soverign's Legacy",
    "uncommon;set4-1": "物理防御力",
    "uncommon;set4-2": "HP",
    "rare;set3-1": "物理防御力",
    "rare;set3-2": "魔法防御力",
    "rare;set4-1": "物理防御力",
    "rare;set4-2": "魔法防御力",
    "rare;set4-3": "HP",
    "legendary;set2-1": "物理攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "物理攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "魔法防御力",
    "legendary;set4-1": "物理攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "魔法防御力",
    "legendary;set4-4": "HP"
  },
  {
    "Talisman": "ラヴェジャーの支配",
    "Talisman_en": "Ravager's Dominiom",
    "uncommon;set4-1": "物理攻撃力",
    "uncommon;set4-2": "HP",
    "rare;set3-1": "物理攻撃力",
    "rare;set3-2": "物理防御力",
    "rare;set4-1": "物理攻撃力",
    "rare;set4-2": "物理防御力",
    "rare;set4-3": "HP",
    "legendary;set2-1": "物理攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "物理攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "魔法防御力",
    "legendary;set4-1": "物理攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "魔法防御力",
    "legendary;set4-4": "HP"
  },
  {
    "Talisman": "神聖なる盾",
    "Talisman_en": "Divine Aegis",
    "uncommon;set4-1": "HP",
    "uncommon;set4-2": "回復倍率",
    "rare;set3-1": "物理防御力",
    "rare;set3-2": "HP",
    "rare;set4-1": "物理防御力",
    "rare;set4-2": "HP",
    "rare;set4-3": "回復倍率",
    "legendary;set2-1": "物理防御力",
    "legendary;set2-2": "魔法防御力",
    "legendary;set3-1": "物理防御力",
    "legendary;set3-2": "魔法防御力",
    "legendary;set3-3": "HP",
    "legendary;set4-1": "物理防御力",
    "legendary;set4-2": "魔法防御力",
    "legendary;set4-3": "HP",
    "legendary;set4-4": "回復倍率"
  },
  {
    "Talisman": "テンペストバウンド",
    "Talisman_en": "Tempestbound",
    "uncommon;set4-1": "物理防御力",
    "uncommon;set4-2": "HP",
    "rare;set3-1": "物理攻撃力",
    "rare;set3-2": "物理防御力",
    "rare;set4-1": "物理攻撃力",
    "rare;set4-2": "物理防御力",
    "rare;set4-3": "HP",
    "legendary;set2-1": "物理攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "物理攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "魔法防御力",
    "legendary;set4-1": "物理攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "魔法防御力",
    "legendary;set4-4": "HP"
  },
  {
    "Talisman": "ブレードウィーバー",
    "Talisman_en": "Bladeweaver",
    "uncommon;set4-1": "物理攻撃力",
    "uncommon;set4-2": "HP",
    "rare;set3-1": "物理攻撃力",
    "rare;set3-2": "物理防御力",
    "rare;set4-1": "物理攻撃力",
    "rare;set4-2": "物理防御力",
    "rare;set4-3": "HP",
    "legendary;set2-1": "物理攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "物理攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "魔法防御力",
    "legendary;set4-1": "物理攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "魔法防御力",
    "legendary;set4-4": "HP"
  },
  {
    "Talisman": "スペルファイア",
    "Talisman_en": "Spellfire",
    "uncommon;set4-1": "魔法攻撃力",
    "uncommon;set4-2": "HP",
    "rare;set3-1": "魔法攻撃力",
    "rare;set3-2": "物理防御力",
    "rare;set4-1": "魔法攻撃力",
    "rare;set4-2": "物理防御力",
    "rare;set4-3": "HP",
    "legendary;set2-1": "魔法攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "魔法攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "魔法防御力",
    "legendary;set4-1": "魔法攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "魔法防御力",
    "legendary;set4-4": "HP"
  },
  {
    "Talisman": "アストラル・コンフラックス",
    "Talisman_en": "Astral Confiux",
    "uncommon;set4-1": "魔法攻撃力",
    "uncommon;set4-2": "MP",
    "rare;set3-1": "魔法攻撃力",
    "rare;set3-2": "HP",
    "rare;set4-1": "魔法攻撃力",
    "rare;set4-2": "HP",
    "rare;set4-3": "MP",
    "legendary;set2-1": "魔法攻撃力",
    "legendary;set2-2": "物理防御力",
    "legendary;set3-1": "魔法攻撃力",
    "legendary;set3-2": "物理防御力",
    "legendary;set3-3": "HP",
    "legendary;set4-1": "魔法攻撃力",
    "legendary;set4-2": "物理防御力",
    "legendary;set4-3": "HP",
    "legendary;set4-4": "MP"
  },
  {
    "Talisman": "セラフィックグレース",
    "Talisman_en": "Seraphic Grace",
    "uncommon;set4-1": "MP",
    "uncommon;set4-2": "回復倍率",
    "rare;set3-1": "HP",
    "rare;set3-2": "MP",
    "rare;set4-1": "HP",
    "rare;set4-2": "MP",
    "rare;set4-3": "回復倍率",
    "legendary;set2-1": "物理防御力",
    "legendary;set2-2": "HP",
    "legendary;set3-1": "物理防御力",
    "legendary;set3-2": "HP",
    "legendary;set3-3": "MP",
    "legendary;set4-1": "物理防御力",
    "legendary;set4-2": "HP",
    "legendary;set4-3": "MP",
    "legendary;set4-4": "回復倍率"
  },
  {
    "Talisman": "勇気の砦",
    "Talisman_en": "Fortress of Valor",
    "uncommon;set4-1": "MP再生",
    "uncommon;set4-2": "回避",
    "rare;set3-1": "MP再生",
    "rare;set3-2": "回避",
    "rare;set4-1": "MP再生",
    "rare;set4-2": "回避",
    "rare;set4-3": "移動速度",
    "legendary;set2-1": "HP再生",
    "legendary;set2-2": "MP再生",
    "legendary;set3-1": "HP再生",
    "legendary;set3-2": "MP再生",
    "legendary;set3-3": "回避",
    "legendary;set4-1": "HP再生",
    "legendary;set4-2": "MP再生",
    "legendary;set4-3": "回避",
    "legendary;set4-4": "移動速度"
  },
  {
    "Talisman": "ドラゴンクロー",
    "Talisman_en": "Dragonclaw",
    "uncommon;set4-1": "命中",
    "uncommon;set4-2": "クリティカル発生率",
    "rare;set3-1": "命中",
    "rare;set3-2": "クリティカル発生率",
    "rare;set4-1": "命中",
    "rare;set4-2": "クリティカル発生率",
    "rare;set4-3": "クリティカル倍率",
    "legendary;set2-1": "HP再生",
    "legendary;set2-2": "命中",
    "legendary;set3-1": "HP再生",
    "legendary;set3-2": "命中",
    "legendary;set3-3": "クリティカル発生率",
    "legendary;set4-1": "HP再生",
    "legendary;set4-2": "命中",
    "legendary;set4-3": "クリティカル発生率",
    "legendary;set4-4": "クリティカル倍率"
  },
  {
    "Talisman": "エルドリッチ・カタリスト",
    "Talisman_en": "Eldritch Catalyst",
    "uncommon;set4-1": "MP再生",
    "uncommon;set4-2": "クリティカル発生率",
    "rare;set3-1": "HP再生",
    "rare;set3-2": "MP再生",
    "rare;set4-1": "HP再生",
    "rare;set4-2": "MP再生",
    "rare;set4-3": "クリティカル発生率",
    "legendary;set2-1": "HP再生",
    "legendary;set2-2": "MP再生",
    "legendary;set3-1": "HP再生",
    "legendary;set3-2": "MP再生",
    "legendary;set3-3": "クリティカル発生率",
    "legendary;set4-1": "HP再生",
    "legendary;set4-2": "MP再生",
    "legendary;set4-3": "クリティカル発生率",
    "legendary;set4-4": "クリティカル倍率"
  },
  {
    "Talisman": "神聖なる調和",
    "Talisman_en": "Divine Harmony",
    "uncommon;set4-1": "HP再生",
    "uncommon;set4-2": "MP再生",
    "rare;set3-1": "HP再生",
    "rare;set3-2": "MP再生",
    "rare;set4-1": "HP再生",
    "rare;set4-2": "MP再生",
    "rare;set4-3": "回復倍率",
    "legendary;set2-1": "HP再生",
    "legendary;set2-2": "MP再生",
    "legendary;set3-1": "HP再生",
    "legendary;set3-2": "MP再生",
    "legendary;set3-3": "回避",
    "legendary;set4-1": "HP再生",
    "legendary;set4-2": "MP再生",
    "legendary;set4-3": "回避",
    "legendary;set4-4": "回復倍率"
  }
];
